service: aws-sqs-python

frameworkVersion: '2'
  
provider:
  name: aws
  region: sa-east-1
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt: [ workerQueue, Arn ]

functions:
  producer:
    handler: handler.producer
    name: ${sls:stage}-python-producer
    events:
      - http:
          method: post
          path: produce
    environment:
      QUEUE_URL:
        Ref: workerQueue

  consumer:
    handler: handler.consumer
    name: ${sls:stage}-python-consumer
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - workerQueue
              - Arn

resources:
  Resources:
    workerQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: workerQueue
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - workerQueueDLQ
              - Arn
          maxReceiveCount: 5
    workerQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: workerQueueDLQ